### ISSUE TITLE
Should `dap` mappings also a dependency for `nvim-dap-python`?

### ISSUE THREAD

**Issue by eric-tramel** [dreamsofcode-io/neovim-python#1]
Thanks for the video & repo, this has been a very fun little afternoon project to get Nvim and running for python using your approach, here :) 

Following through with your implementation, I ran into an issue -- I couldn't get the `dap` break points mapping to work. It seems like there  may be some order of operations issue in making sure that the `dap`-level mappings _also_ get imported when viewing a python file.

As configured here, I was able to get debugpy's run to execute via `<leader>dpr` as configured -- but there was no way to get the breakpoint to work!

I updated my local re-implementation to get breakpoints to work with `<leader>dp` by forcing an additional requirement of the `dap` mappings when configuring the `nvim-dap-python` plugin:

```lua
  {
    "mfussenegger/nvim-dap-python",
    ft = "python",
    dependencies = {
      "mfussenegger/nvim-dap",
      "rcarriga/nvim-dap-ui",
    },
    config = function(_, opts)
      local path = "~/.local/share/nvim/mason/packages/debugpy/venv/bin/python"
      require("dap-python").setup(path)
      require("core.utils").load_mappings("dap")
      require("core.utils").load_mappings("dap_python")
    end,
  }
```

**Comment by elliottminns** [comment]
Typically it should work when loading the `nvim-dap` plugin. I'll check the code and see what's up!

**Comment by elliottminns** [comment]
Verified this is working as expected with the current setup
