### ISSUE TITLE
nvim-dap-python configuration not working

### ISSUE THREAD

**Issue by hailuand** [dreamsofcode-io/neovim-python#10]
Hello, and thanks for the stellar nvim content!

I've followed the video using the 2.0 branch of NvChad, but am having problems during the debugging section. I get the following error when performing space + dpr:

![image](https://github.com/dreamsofcode-io/neovim-python/assets/6646502/31305e42-8518-4dc9-b252-452c66d415c1)

Running it through the command line seems alright:
```shell
❯ python3 primes_test.py
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```

My `primes.py`:

```python3
from typing import List


def primes(n: int) -> List:
    # return a list of the first n primes
    sieve = [True] * n
    res = []
    for i in range(2, n):
        if sieve[i]:
            res.append(i)
            for j in range(i * i, n, i):
                sieve[j] = False
    return res


xs = primes(100)
print(xs)
```

And `primes_test.py`:
```python3
import unittest
from primes import primes


class TestPrimes(unittest.TestCase):
    def test_primes(self):
        self.assertEqual(primes(10), [2, 3, 5, 7])


if __name__ == "__main__":
    unittest.main()
```

Been scratching my head a bit on this.

I've copied + pasted the latest configs from this repo as well to see if I had a typo somewhere.

The only difference I can make out is that NeoVim prompted me to install `nvim-neotest/nvim-nio` in order to use dap-ui, which isn't present in this repo as is (happy to make a PR!)

**Comment by elliottminns** [comment]
The error suggests it's missing a positional argument in the Primes code. Although your test does seem to have it.

I wonder if the command is attempting to invoke the actual primes function itself?

**Comment by hailuand** [comment]
Seems to work just fine if I run the test directly from the test class. 

[In the video](https://youtu.be/4BnVeOUeZxc?si=PDKPOR868n7YlpA3&t=868), it appeared that you were able to run space + dpr on the actual method and the corresponding test method was executed, which is what I was trying to do.
